import { Observable } from "rxjs"
import { SUSPENSE } from "../SUSPENSE"
import connectFactoryObservable from "./connectFactoryObservable"
import connectObservable from "./connectObservable"

/**
 * Binds an observable to React
 *
 * @param observable Source observable to be used by the hook.
 * @param unsubscribeGraceTime (= 200): Amount of time in ms that the shared
 * observable should wait before unsubscribing from the source observable when
 * there are no new subscribers.
 * @returns [1, 2]
 * 1. A React Hook that yields the latest emitted value of the observable
 * 2. A `sharedLatest` version of the observable. It can be used for composing
 * other streams that depend on it. The shared subscription is closed as soon as
 * there are no subscribers to that observable.
 *
 * @remarks If the Observable doesn't synchronously emit a value upon the first
 * subscription, then the hook will leverage React Suspense while it's waiting
 * for the first value.
 */
export function bind<T>(
  observable: Observable<T>,
  unsubscribeGraceTime?: number,
): [() => Exclude<T, typeof SUSPENSE>, Observable<T>]

/**
 * Binds a factory observable to React
 *
 * @param getObservable Factory of observables. The argument of this function
 *  will be the key used in the hook.
 * @param unsubscribeGraceTime (= 200): Amount of time in ms that the shared
 *  observable should wait before unsubscribing from the source observable when
 *  there are no new subscribers.
 * @returns [1, 2]
 * 1. A React Hook function that takes a key as a parameter.
 *  This hook will yield the latest update from the observable returned from
 *  the factory function.
 * 2. A `sharedLatest` version of the observable generated by the factory
 *  function that can be used for composing other streams that depend on it.
 *  The shared subscription is closed as soon as there are no subscribers to
 *  that observable.
 *
 * @remarks If the Observable doesn't synchronously emit a value upon the first
 * subscription, then the hook will leverage React Suspense while it's waiting
 * for the first value.
 */
export function bind<K, O>(
  getObservable: (key: K) => Observable<O>,
  unsubscribeGraceTime?: number,
): [(key: K) => Exclude<O, typeof SUSPENSE>, (key: K) => Observable<O>]

export function bind<K, O>(
  obs: ((key: K) => Observable<O>) | Observable<O>,
  unsubscribeGraceTime = 200,
) {
  return (typeof obs === "function"
    ? (connectFactoryObservable as any)
    : connectObservable)(obs, unsubscribeGraceTime)
}
