import { Observable, NEVER, concat } from "rxjs"
import { distinctShareReplay } from "./operators/distinct-share-replay"
import reactEnhancer from "./operators/react-enhancer"
import { ConnectorOptions, defaultConnectorOptions } from "./options"
import { BehaviorObservable } from "./BehaviorObservable"
import { SUSPENSE } from "./SUSPENSE"
import { useObservable } from "./useObservable"

/**
 * Accepts: A factory function that returns an Observable.
 *
 * Returns [1, 2]
 * 1. A React Hook function with the same parameters as the factory function.
 *  This hook will yield the latest update from the observable returned from
 *  the factory function.
 * 2. A shared replayable version of the observable generated by the factory
 *  function that can be used for composing other streams that depend on it.
 *  This observable is disposed when its refCount goes down to zero.
 *
 * @param getObservable Factory of observables. The arguments of this function
 *  will be the ones used in the hook.
 * @param options ConnectorOptions:
 *  - unsubscribeGraceTime (= 200): Amount of time in ms that the shared
 *    observable should wait before unsubscribing from the source observable
 *    when there are no new subscribers.
 *  - compare (= Object.is): Equality function.
 */
export function connectFactoryObservable<
  A extends (number | string | boolean | null)[],
  O
>(
  getObservable: (...args: A) => Observable<O>,
  options?: ConnectorOptions<O>,
): [
  (...args: A) => Exclude<O, typeof SUSPENSE>,
  (...args: A) => Observable<O>,
] {
  const _options = {
    ...defaultConnectorOptions,
    ...options,
  }

  const cache = new Map<
    string,
    [BehaviorObservable<O>, BehaviorObservable<O>]
  >()

  const getSharedObservables$ = (
    ...input: A
  ): [BehaviorObservable<O>, BehaviorObservable<O>] => {
    const key = JSON.stringify(input)
    const cachedVal = cache.get(key)

    if (cachedVal !== undefined) {
      return cachedVal
    }

    const sharedObservable$ = distinctShareReplay(_options.compare, () => {
      cache.delete(key)
    })(concat(getObservable(...input), NEVER))

    const reactObservable$ = reactEnhancer(
      sharedObservable$,
      _options.unsubscribeGraceTime,
    )
    const result: [BehaviorObservable<O>, BehaviorObservable<O>] = [
      sharedObservable$,
      reactObservable$,
    ]

    cache.set(key, result)
    return result
  }
  const getSharedObservable$ = (...input: A) =>
    getSharedObservables$(...input)[0]

  return [
    (...input: A) => useObservable(getSharedObservables$(...input)[1]),

    getSharedObservable$,
  ]
}
