export { connectObservable } from "./connectObservable"
export { connectFactoryObservable } from "./connectFactoryObservable"
export { connectInstanceObservable } from "./connectInstanceObservable"
export { default as distinctShareReplay } from "./operators/distinct-share-replay"
export { default as useSharedReplayableObservable } from "./useSharedReplayableObservable"
